# Standards: 0.1
---
- hosts: all

  remote_user: root

  gather_facts: no

  pre_tasks:
  - name: Install Packages
    yum:
      name: "{{ item }}"
      update_cache: yes
    register: pkgstatus
    until: pkgstatus is succeeded
    with_items:
    - initscripts
    - iproute
    - rsyslog

  - name: Enable Services
    service:
      name: "{{ item }}"
      state: started
    with_items:
    - rsyslog
