---
language: python

cache:
  directories:
    - /home/travis/.rvm
    - /home/travis/.cache/pip
    - /home/travis/virtualenv

python: 3.6

# Install ansible
install:
  - bundle install
  - pip uninstall --yes ansible
  - pip install -Ur requirements-latest.txt
  - pip freeze

script:
  - bundle exec rubocop -ES
  - molecule test --scenario-name latest --destroy never

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
      - https://webhooks.gitter.im/e/eee7ec1dcb85c454573a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

jobs:
  include:
    - env: COMMAND="/usr/sbin/init"
           DISTRO="centos"
           TAG=latest
    - env: DISTRO="debian"
           TAG=stable
    - env: COMMAND="/usr/sbin/init"
           DISTRO="fedora"
           TAG=latest
    - env: DISTRO="ubuntu"
           TAG=latest
