---
language: python

cache:
  directories:
    - /home/travis/.rvm
    - /home/travis/.cache/pip
    - /home/travis/virtualenv

python: 3.6

# Install ansible
install:
  - ./.travis/install

script:
  - ./.travis/script

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
      - https://webhooks.gitter.im/e/eee7ec1dcb85c454573a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

jobs:
  include:
    - env: HOSTS="centos"
    - env: HOSTS="debian"
    - env: HOSTS="fedora"
    - env: HOSTS="ubuntu"
