---
language: python

sudo: true

cache:
  directories:
  - /home/travis/.rvm
  - /home/travis/.cache/pip
  - /home/travis/virtualenv

# Install ansible
install:
  - bundle install
  - pip install -Ur requirements.txt

script:
  - make lint
  - molecule --debug test -s $SCENARIO

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

# Fedora 29 uses Python 3.7 but this is not available on TravisCI yet.
matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: SCENARIO="default"
  - python: 2.7
    env: SCENARIO="debian9"
  - python: 2.7
    env: SCENARIO="ubuntu1604"
  - python: 2.7
    env: SCENARIO="ubuntu1804"
  - python: 3.6
    env: SCENARIO="fedora28"
  - python: 3.6
    env: SCENARIO="fedora29"
