---
language: python

arch: arm64-graviton2
dist: focal
os: linux
python: 3.8.6
virt: vm


# Skip builds on tag pushes
if: tag IS blank

cache:
  directories:
    - /home/travis/.rvm
    - /home/travis/.cache/pip
    - /home/travis/virtualenv

# Install ansible
install:
  - bundle install
  - pip install -Ur requirements.txt
  - pip freeze

script:
  - bundle exec rubocop -ES
  - molecule test --destroy never
  - molecule test --scenario-name combine_cluster --destroy never

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
      - https://webhooks.gitter.im/e/eee7ec1dcb85c454573a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

jobs:
  include:
    - env: COMMAND="/usr/sbin/init"
           DISTRO="centos"
           TAG=7
    - env: COMMAND="/usr/sbin/init"
           DISTRO="centos"
           TAG=8
    - env: DISTRO="debian"
           TAG=9
    - env: DISTRO="debian"
           TAG=10
    - env: COMMAND="/usr/sbin/init"
           DISTRO="fedora"
           TAG=32
    - env: COMMAND="/usr/sbin/init"
           DISTRO="fedora"
           TAG=33
    - env: DISTRO="ubuntu"
           TAG=18.04
    - env: DISTRO="ubuntu"
           TAG=20.04
