---
language: python

sudo: true

cache:
  directories:
    - /home/travis/.rvm
    - /home/travis/.cache/pip
    - /home/travis/virtualenv

# Install ansible
install:
  - ln -s $( basename $PWD ) ../locp.cassandra
  - bundle install
  - pip install -Ur requirements.txt

script:
  - make

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: SCENARIO="default"
    - python: 3.6
      env: SCENARIO="debian9"
    - python: 3.6
      env: SCENARIO="ubuntu"
    - python: 3.6
      env: SCENARIO="fedora"
