---
language: python

sudo: true

cache:
  directories:
    - /home/travis/.rvm
    - /home/travis/.cache/pip
    - /home/travis/virtualenv

# Install ansible
install:
  - ln -s $( basename $PWD ) ../locp.cassandra
  - bundle install
  - pip install -Ur requirements.txt
  - pip freeze

script:
  - make

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
      - https://webhooks.gitter.im/e/eee7ec1dcb85c454573a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: HOSTS="centos"
    - python: 3.6
      env: HOSTS="debian"
    - python: 3.6
      env: HOSTS="fedora"
    - python: 3.6
      env: HOSTS="ubuntu"
