---
language: python

sudo: true

cache:
  directories:
  - /home/travis/.rvm
  - /home/travis/.cache/pip
  - /home/travis/virtualenv

# Install ansible
install:
  - bundle install
  - pip install -Ur requirements.txt

script:
  - make lint
  - bundle exec kitchen create $PLATFORM || true # A minor schlonk to avoid failure during kitchen build.
  - bundle exec kitchen test "check-${PLATFORM}"
  - bundle exec kitchen test "default-${PLATFORM}"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

# Fedora 29 uses Python 3.7 but this is not available on TravisCI yet.
matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: PLATFORM="centos-7"
  - python: 2.7
    env: PLATFORM="debian-9"
  - python: 2.7
    env: PLATFORM="ubuntu-1604"
  - python: 2.7
    env: PLATFORM="ubuntu-1804"
  - python: 3.6
    env: PLATFORM="fedora-28"
  - python: 3.6
    env: PLATFORM="fedora-29"
