---
language: python

sudo: true

cache:
  directories:
  - /home/travis/.rvm
  - /home/travis/.cache/pip
  - /home/travis/virtualenv

addons:
  apt:
    packages:
    - python-pip
    - ruby-bundler

# Install ansible
install:
  - bundle install
  - pip install -r requirements.txt

  # Check versions
  - ansible --version
  - ansible-lint --version
  - rubocop --version

script:
  - make lint
  - bundle exec kitchen list
  - bundle exec kitchen test $INSTANCE

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: INSTANCE="Redhat-centos"
  - python: 2.7
    env: INSTANCE="Check-centos"
  - python: 2.7
    env: INSTANCE="Check-ubuntu-1604"
  - python: 2.7
    env: INSTANCE="Debian-ubuntu-1604"
