---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -ex
  yamllint -s .
  ansible-lint
  flake8

platforms:
  - name: node0
    command: ${COMMAND:-"sleep infinity"}
    dockerfile: ../default/Dockerfile.j2
    groups:
      - cassandra
      - clustered
      - ${DISTRO:-debian}${TAG:-stable}
    image: ${DISTRO:-debian}:${TAG:-stable}
    privileged: True

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: "profile_tasks,timer"

  inventory:
    group_vars:
      centoslatest:
        ansible_python_interpreter: python3
        cassandra_systemd_enabled: True
      debianstable:
        cassandra_15770_workaround: True
      fedora32:
        ansible_python_interpreter: python3
        cassandra_systemd_enabled: True
      fedora33:
        ansible_python_interpreter: python3
        cassandra_systemd_enabled: True
      ubuntu18.04:
      ubuntu20.04:
        cassandra_15770_workaround: True

  log: True

  options:
    v: 1

scenario:
  test_sequence:
    # Pretty much the default test sequence, just added the check step.
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - idempotence
    - verify

verifier:

  name: testinfra

  options:
    connection: docker
    durations: 3
    v: 1
