---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-data:
      ignore: molecule/default/molecule.yml

platforms:
  - name: centos
    dockerfile: Dockerfile-centos8.j2
    groups:
      - python3
    image: centos:latest

  - name: debian
    image: debian:latest

  - name: fedora
    dockerfile: Dockerfile-centos8.j2
    groups:
      - python3
    image: fedora:latest

  - name: ubuntu
    image: ubuntu:latest

provisioner:
  name: ansible

  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: python3

  lint:
    name: ansible-lint

verifier:
  name: testinfra
  lint:
    name: flake8
