---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    command: /usr/sbin/init
    image: centos:7
    privileged: True
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - check
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  options:
    v: 1
  lint:
    name: flake8
