---
- hosts: all

  remote_user: root

  vars:
    instance_key: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}"
    packages:
      CentOS7:
        - initscripts
        - iproute
      Debian9:
        - apt-utils
        - lsb-release
        - procps
        - python-apt
      Fedora28:
        - initscripts
        - iproute
        - java-1.8.0-openjdk-headless
      Fedora29:
        - initscripts
        - iproute
        - java-1.8.0-openjdk-headless
      Ubuntu16:
        - apt-utils
        - iproute
        - python-apt
      Ubuntu18:
        - apt-utils
        - iproute2
        - python-apt
    instance_info:
      ansible_distribution: "{{ ansible_distribution }}"
      ansible_distribution_major_version: "{{ ansible_distribution_major_version }}"
      ansible_os_family: "{{ ansible_os_family }}"

  tasks:
    - name: Display Host Information
      debug:
        var: instance_info

    - name: Install EPEL
      yum:
        name: epel-release
        update_cache: yes
      register: pkgstatus
      until: pkgstatus is succeeded
      when: ansible_distribution == 'CentOS'

    - name: Install Yum Packages
      yum:
        name: "{{ packages[instance_key] }}"
        update_cache: yes
      register: pkgstatus
      until: pkgstatus is succeeded
      when: ansible_distribution == 'CentOS'

    - name: Install Fedora Packages
      package:
        name: "{{ packages[instance_key] }}"
      register: pkgstatus
      until: pkgstatus is succeeded
      when: ansible_distribution == 'Fedora'

    - name: Install Debian Packages
      apt:
        name: "{{ packages[instance_key] }}"
        update_cache: yes
      delay: 10
      register: pkgstatus
      retries: 5
      until: pkgstatus is succeeded
      when: ansible_os_family == 'Debian'
