---
- hosts: all

  remote_user: root

  vars:
    instance_key: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}"
    packages:
      CentOS7:
        - initscripts
        - iproute
      CentOS8:
        - initscripts
        - iproute
        - java-1.8.0-openjdk-headless
      Debian9:
        - apt-utils
        - lsb-release
        - procps
        - python-apt
      Debian10:
        - apt-utils
        - lsb-release
        - procps
        - python-apt
      Fedora29:
        - initscripts
        - iproute
        - java-1.8.0-openjdk-headless
      Fedora30:
        - initscripts
        - iproute
        - java-1.8.0-openjdk-headless
      Ubuntu16:
        - apt-utils
        - iproute
        - python-apt
      Ubuntu18:
        - apt-utils
        - iproute2
        - python-apt
    instance_info:
      ansible_distribution: "{{ ansible_distribution }}"
      ansible_distribution_major_version: "{{ ansible_distribution_major_version }}"
      ansible_os_family: "{{ ansible_os_family }}"

  tasks:
    - name: Display Host Information
      debug:
        var: instance_info

    - name: Install EPEL for CentOS
      package:
        name: epel-release
      register: pkgstatus
      until: pkgstatus is succeeded
      when:
        - ansible_distribution == 'CentOS'

    - name: Install RedHat Packages
      package:
        name: "{{ packages[instance_key] }}"
      register: pkgstatus
      until: pkgstatus is succeeded
      notify: Reinstall iproute and libmnl
      when: ansible_os_family == 'RedHat'

    - name: Install Debian Packages
      apt:
        name: "{{ packages[instance_key] }}"
        update_cache: yes
      delay: 10
      register: pkgstatus
      retries: 5
      until: pkgstatus is succeeded
      when: ansible_os_family == 'Debian'

    - name: Debian 10 Add Azul Key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: B1998361219BD9C9
      register: cassandra_remote_status
      until: cassandra_remote_status is succeeded
      when:
        - ansible_os_family == 'Debian'
        - ansible_distribution_major_version == '10'

    - name: Debian 10 Configure Azul Repository
      apt_repository:
        filename: /etc/apt/sources.list.d/zulu.sources
        repo: "deb http://repos.azulsystems.com/debian stable main"
        state: present
      when:
        - ansible_os_family == 'Debian'
        - ansible_distribution_major_version == '10'

    - name: Debian 10 Install Zulu Java
      apt:
        name: "zulu-8"
        update_cache: yes
      delay: 10
      register: pkgstatus
      retries: 5
      until: pkgstatus is succeeded
      when:
        - ansible_os_family == 'Debian'
        - ansible_distribution_major_version == '10'

  handlers:
    - name: Reinstall iproute and libmnl
      # A hack that only seems to be required on CentOS8.  If this is not
      # called, ansible_default_ipv4 is not populated as a fact (iproute
      # and libmnl) or enable the Cassandra service (initscripts).
      command: dnf reinstall -y initscripts iproute libmnl 
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version == '8'
