---
- hosts: all

  remote_user: root

  vars:
    apt_key: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}"
    apt_packages:
      Debian9:
        - apt-utils
        - lsb-release
        - procps
        - python-apt
      Ubuntu16:
        - apt-utils
        - iproute
        - python-apt
      Ubuntu18:
        - apt-utils
        - iproute2
        - python-apt
    instance_info:
      ansible_distribution: "{{ ansible_distribution }}"
      ansible_distribution_major_version: "{{ ansible_distribution_major_version }}"
      ansible_os_family: "{{ ansible_os_family }}"

  tasks:
    - name: Display Host Information
      debug:
        var: instance_info

    - name: Install EPEL
      yum:
        name: epel-release
        update_cache: yes
      register: pkgstatus
      until: pkgstatus is succeeded
      when: ansible_distribution == 'CentOS'

    - name: Install Yum Packages
      yum:
        name: "{{ item }}"
        update_cache: yes
      register: pkgstatus
      until: pkgstatus is succeeded
      with_items:
        - initscripts
        - iproute
      when: ansible_distribution == 'CentOS'

    - name: Install Fedora Packages
      package:
        name: "{{ item }}"
      register: pkgstatus
      until: pkgstatus is succeeded
      with_items:
        - initscripts
        - iproute
        - java-1.8.0-openjdk-headless
      when: ansible_distribution == 'Fedora'

    - name: Install Debian Packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      delay: 10
      register: pkgstatus
      retries: 5
      until: pkgstatus is succeeded
      with_items: "{{ apt_packages[apt_key] }}"
      when: ansible_os_family == 'Debian'
