# Standards: 0.1
---
- hosts: all

  remote_user: root

  pre_tasks:
  - name: Set Some Instance Facts
    set_fact:
      instance_facts:
        distribution: "{{ ansible_facts['distribution'] }}"
        hostname: "{{ ansible_hostname }}"
        os_family: "{{ ansible_facts['os_family'] }}"

  - name: Show Instance Facts
    debug:
      var: instance_facts

  - name: Install Packages
    package:
      name: "{{ item }}"
    with_items:
    - apt-utils
    - python-apt
