---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu1804
    dockerfile: ../default/Dockerfile.j2
    image: ubuntu:18.04
    groups:
      - cassandra
    privileged: True
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
  playbooks:
    converge: ../default/playbook.yml
    prepare: ../default/prepare.yml
scenario:
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - idempotence
    - verify
verifier:
  name: testinfra
  directory: ../default/tests
  lint:
    name: flake8
  options:
    v: 1
