---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
- name: fedora-29
  command: /usr/sbin/init
  image: fedora:29
  privileged: True
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
  playbooks:
    converge: ../default/playbook.yml
scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - check
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  directory: ../default/tests
  lint:
    name: flake8
  options:
    v: 1
