---
- hosts: all

  remote_user: root

  gather_facts: no

  pre_tasks:
    - name: Install Packages
      apt:
        name: "{{ item }}"
        cache_valid_time: 600
      register: pkgstatus
      until: pkgstatus is succeeded
      with_items:
        - apt-utils
        - iproute
        - python-apt
