---
name: CI CentOS 8

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy the Initial Clusters
      run: DISTRO="centos" TAG=8 molecule test --destroy never

    - name: Combine the Clusters
      run: DISTRO="centos" TAG=8 molecule test --scenario-name combine_cluster --destroy never
