---
name: CI Debian 10

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy the Initial Clusters
      env:
        DISTRO: debian
        TAG: 10
      run: molecule test --destroy never

    - name: Combine the Clusters
      env:
        DISTRO: debian
        TAG: 10
      run: molecule test --scenario-name combine_cluster
