---
name: CI Fedora 32

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy the Initial Clusters
      env:
        COMMAND: /usr/sbin/init
        DISTRO: fedora
        TAG: 34
      run: molecule test --destroy never

    - name: Combine the Clusters
      env:
        COMMAND: /usr/sbin/init
        DISTRO: fedora
        TAG: 34
      run: molecule test --scenario-name combine_cluster
