---
name: Latest Components

on:
  push:
    branches: [ feature/latest ]
  schedule:
    - cron:  '0 0 1,15 * *'

jobs:
  molecule:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - distro: centos
            command: /usr/sbin/init
            tag: latest
          - distro: debian
            command: "sleep infinity"
            tag: stable
          - distro: fedora
            command: "/usr/sbin/init"
            tag: latest
          - distro: ubuntu
            command: "sleep infinity"
            distro: ubuntu
            tag: latest
    steps:
    - uses: actions/checkout@v2

    # - uses: actions/cache@v2
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-latest.txt
        pip freeze

    - name: Deploy the Initial Clusters
      env:
        COMMAND: "${{ matrix.command }}"
        DISTRO: "${{ matrix.distro }}"
        TAG: "${{ matrix.tag }}"
      run: molecule test --scenario-name latest --destroy never
