---
name: Publish the Role to Galaxy

on:
  push:
    branches:
      - main

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ansible Galaxy Import
        run: |
          ansible-galaxy role import --api-key "${GALAXY_API_KEY}" --branch main --role-name cassandra locp ansible-role-cassandra
        env:
          GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
