---
name: Publish the Role to Galaxy

on:
  push:
    branches:
      - bugfix/git_workflow_publish
      - main

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ansible Galaxy Import
        run: |
          ansible-galaxy role import --api-key "${GALAXY_API_KEY}" --branch "${GITHUB_REF}" --role-name cassandra locp ansible-role-cassandra
        env:
          GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
